apiVersion: v1
kind: Service
metadata:
    name: apa000ser
spec:
    type: NodePort
    selector:
        app: apa000kube
    ports:
    - port: 8099
      protocol: TCP
      targetPort: 80
      nodePort: 30080
